# compiler

FC = ifort #

FFLAGS = -fPIC -shared

SYSTEM_MOD = system_mod.f90 

#all: fortran_compute_rdf.so 

fortran_compute_rdf.so: compute_rdf_mod.f90 

	$(FC) $(FFLAGS) $(SYSTEM_MOD) compute_rdf_mod.f90  -o fortran_compute_rdf.so 

# print the variable
#$(info $(FC))
#


