#!/bin/bash 

# intel compiler is used to compile fortran program into dynamic library: *.so file    
# ifort -v 

# A compiler supporting Fortran 2003 standard is needed:  
# compilers used in my machine:
# ifort = 18.0.3 (>12.0) 
# gfortran = 4.8.5   

# Intel fortran compiler (Recommended): 

ifort -fPIC -shared system_mod.f90 dcd_reader_mod.f90  -o fortran_dcd_reader.so 
ifort -fPIC -shared system_mod.f90 txt_reader_mod.f90  -o fortran_txt_reader.so 
ifort -fPIC -shared system_mod.f90 xyz_reader_mod.f90  -o fortran_xyz_reader.so

# GNU fortran compilers (not compatiable with current fortran module): 

#gfortran -fPIC -shared system_mod.f90 dcd_reader_mod.f90  -o fortran_dcd_reader.so 
#gfortran -fPIC -shared system_mod.f90 txt_reader_mod.f90  -o fortran_txt_reader.so 
